collections:
  - name: ansible.netcommon       # Removed version pin
  - name: ansible.utils
    version: "2.10.3"
  - name: ansible.windows
    version: "3.0.0"
  - name: cisco.asa
    version: "6.1.0"
  - name: cisco.fmcansible
    version: "1.0.2"
  - name: cisco.ios
    version: "10.0.0"
  - name: cisco.ise
    version: "2.10.0"
  - name: community.general
    version: "10.6.0"
  - name: community.network
    version: "5.0.0"
  - name: fortinet.fortios
    version: "2.4.0"
  - name: paloaltonetworks.panos
    version: "3.0.0"

