---
collections:
  - name: ansible.netcommon
    version: 5.1.1
  - name: ansible.utils
    version: 2.10.3
  - name: cisco.fmcansible
    version: 1.0.2
  - name: cisco.ise
    version: 2.10.0
  - name: cisco.asa
  - name: cisco.ios
  - name: community.general
  - name: community.network
  - name: fortinet.fortios
  
