---
- name: BACKUP ROUTER CONFIGURATIONS
  hosts: switch
  connection: network_cli
  gather_facts: no
  become: yes
  become_method: enable

  tasks:
    - name: BACKUP THE CONFIG
      ios_config:
        backup: yes
      register: config_output

    - name: DISPLAY BACKUP FILE PATH
      debug:
        var: config_output.backup_path

