- name: Configure OSPF
  hosts: asav
  gather_facts: no
  connection: network_cli

  vars:
    ansible_network_os: cisco.asa.asa
    ansible_user: admin
    ansible_password: admin
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: admin

  tasks:
    - name: Configure OSPF
      asa_command:
        commands:
          - router ospf 1
          - network 172.29.16.0 255.255.255.0 area 0
          - log-adj-changes
