- name: Configure interface settings
  hosts: asav
  gather_facts: no
  connection: network_cli

  vars:
    ansible_network_os: cisco.asa.asa
    ansible_user: admin
    ansible_password: admin
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: admin

  tasks:
    - name: Configure interface settings
      asa_command:
        commands:
          - config t
          - interface GigabitEthernet0/0
          - nameif mgmt
          - security-level 100
          - ip address 172.29.16.1 255.255.255.0
          - no shutdown
          - interface GigabitEthernet0/1
          - nameif outside
          - security-level 0
          - ip address 5.2.18.1 255.255.255.0
          - no shutdown

