---
- name: Configure FortiGate interfaces, LDAP, static routes, local users, VPN, and policies
  hosts: fortigates
  connection: httpapi
  gather_facts: no
  collections:
    - fortinet.fortios

  vars:
    ansible_httpapi_use_ssl: no
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 80
    vdom: "root"
    fortigate_token: "99kjN6p6H3N4xdHd51xtQy9p7g4wGh"

  tasks:

    - name: Configure interfaces
      fortios_system_interface:
        vdom: "{{ vdom }}"
        state: "present"
        system_interface: "{{ item }}"
        access_token: "{{ fortigate_token }}"
      loop:
        - name: "port1"
          ip: "150.1.7.105 255.255.255.0"
          allowaccess: ["ping", "https", "ssh", "http"]
          type: "physical"
          snmp_index: 1
        - name: "port2"
          ip: "172.29.8.1 255.255.255.0"
          allowaccess: ["ping", "https", "ssh", "http"]
          type: "physical"
          alias: "lan"
          device_identification: "enable"
          lldp_transmission: "enable"
          role: "lan"
          snmp_index: 2
          ipv6:
            ip6_send_adv: "enable"
            ip6_other_flag: "enable"
        - name: "port3"
          ip: "5.2.11.1 255.255.255.0"
          allowaccess: ["ping", "https", "ssh", "http"]
          type: "physical"
          alias: "wan"
          lldp_reception: "enable"
          role: "wan"
          snmp_index: 3
          ipv6:
            ip6_send_adv: "enable"
            ip6_other_flag: "enable"
        - name: "naf.root"
          type: "tunnel"
          src_check: "disable"
          snmp_index: 5
        - name: "l2t.root"
          type: "tunnel"
          snmp_index: 6
        - name: "ssl.root"
          type: "tunnel"
          alias: "SSL VPN interface"
          snmp_index: 7

    - name: Configure LDAP server
      fortios_user_ldap:
        vdom: "{{ vdom }}"
        state: present
        user_ldap:
          name: "sales-LDAP"
          server: "150.1.7.10"
          cnid: "cn"
          dn: "dc=pfe,dc=lab"
          type: "regular"
          username: "sale01"
          password: "ENC MTAwNCz09QsuQ2BrdJJupHvM+pM/1GOyvPnCDCfOHdwImW/hJnhQrjv3XqwSowS7GlAzJnyM6/k4qQZi0VMUSJDs/oT0pBWtRnQNbSAwmFS+aeH9fr00lxKGZBTCQOfEDLfNtw94B71IS06C9aS+nFn+13A/2cZwqtlQRifkUH8E/skOHJJunjc4bJ804nEmugQUSw=="
        access_token: "{{ fortigate_token }}"

    - name: Configure static routes
      fortios_router_static:
        vdom: "{{ vdom }}"
        state: present
        router_static: "{{ item }}"
        access_token: "{{ fortigate_token }}"
      loop:
        - seq_num: 1
          device: "port1"
          gateway: "150.1.7.55"
        - seq_num: 2
          dst: "192.168.1.1 255.255.255.255"
          device: "port2"
          gateway: "172.29.8.254"
        - seq_num: 3
          dst: "172.29.10.0 255.255.255.0"
          device: "port3"
          gateway: "5.2.11.254"
        - seq_num: 4
          dst: "172.29.0.0 255.255.0.0"
          device: "port2"
          gateway: "172.29.8.254"

    - name: Configure local users
      fortios_user_local:
        vdom: "{{ vdom }}"
        state: present
        user_local: "{{ item }}"
        access_token: "{{ fortigate_token }}"
      loop:
        - name: "guest"
          type: "password"
          passwd: "ENC JnDBawxifLav191gbNE9hfUN4VBWynAp2LPmcdov1HBQXbK9h8Z8vuMZ2U/FIeKNjAtQdbD5DfBRoAFkhmv5Fjjy8eopoZuQUUPCiJhQ8NEcLU3vvn0/xeDIuTs4Pc3fmm21/uAxixDRYG953R6+ok+U3UoyiI9WPPNdpysmQ/oYz2Vcdz913X9JeV9wFYnktpfNtg=="
        - name: "admin"
          type: "password"
          passwd_time: "2025-02-18 09:22:03"
          passwd: "ENC efDVO4L5CE2E8GmsnaLxVDGNvCuylFhhi1c/X1tiPuA6NdHX05f2B+tnH9z48AoIWYmSNTCSvb3FxegaTVD08Njk2Yyu6otwUPuGR61zv8Tpdd8fpOUYKU69oQueMMsPiP0FQmmuwqRccy20oGblQx4C7pSb8qMmpafTGnHEvS3o3+OfI+82wom68HZmlTF4lhgxpg=="
        - name: "hessen"
          type: "password"
          passwd_time: "2025-02-20 06:52:25"
          passwd: "ENC 1J1OAByIwY9WjVuDfUCUIOf+iVUfgHlvmvyyFWW4yVuIQcdgC6W3zV2LHrMNxSRFrgi1uIiKUETC6LYljKMN6a/f45z0xBn9llLx4hB0rTxy/kPYH8VIMfWRpxBrRK1Z8AAToSlaaekwEYGfFgGh+rPwu/3E1KlZnwgCIGhlyLbB6qoBcMMzultv4aMSmhcI18yDhA=="

    

    - name: Configure SSL VPN settings
      fortios_vpn_ssl_settings:
        vdom: "{{ vdom }}"
        vpn_ssl_settings:
          servercert: "ok"
          tunnel_ip_pools: ["ssl-vpn"]
          port: 20443
          source_interface: ["port3"]
          source_address: ["all"]
          source_address6: ["all"]
          default_portal: "full-access"
          
            
              
           
              
        access_token: "{{ fortigate_token }}"

    - name: Configure firewall policies
      fortios_firewall_policy:
        vdom: "{{ vdom }}"
        state: present
        firewall_policy: "{{ item }}"
        access_token: "{{ fortigate_token }}"
      loop:
        - name: "to-internet"
          policyid: 1
          uuid: "da699c1c-ee19-51ef-e0db-743f3624c962"
          srcintf: ["port3"]
          dstintf: ["port1"]
          action: "accept"
          srcaddr: ["all"]
          dstaddr: ["all"]
          schedule: "always"
          service: ["ALL"]
          logtraffic: "all"
          nat: "enable"
        - name: "sales-vpn-ssl"
          policyid: 2
          uuid: "55b6bad2-ee1d-51ef-fb18-da5e2dd581bd"
          srcintf: ["ssl.root"]
          dstintf: ["port2"]
          action: "accept"
          srcaddr: ["ssl-vpn"]
          dstaddr: ["server"]
          schedule: "always"
          service: ["ALL"]
          logtraffic: "all"
          nat: "enable"
         

