- name: Set enable password
  hosts: asav
  gather_facts: no
  connection: network_cli

  vars:
    ansible_network_os: cisco.asa.asa
    ansible_user: admin
    ansible_password: admin
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: admin

  tasks:
    - name: Set enable password
      asa_command:
        commands:
          - config t
          - enable password admin pbkdf2

