- name: Retrieve Access Policies from FMC
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    fmc_base_url: "https://150.1.7.160"
    fmc_token: "4a75b38f-8df6-424c-b30c-0e954c78aa53"
    domain_uuid: "e276abec-e0f2-11e3-8169-6d9ed49b625f"

  tasks:
    - name: Get Access Policies
      uri:
        url: "{{ fmc_base_url }}/api/fmc_config/v1/domain/{{ domain_uuid }}/policy/accesspolicies"
        method: GET
        headers:
          X-auth-access-token: "{{ fmc_token }}"
          Content-Type: "application/json"
        validate_certs: no
        return_content: yes
        status_code: 200
      register: policies_response

    - name: Display Retrieved Policies
      debug:
        var: policies_response.json

