---
- name: Activate a node in EVE-NG using curl
  hosts: localhost
  gather_facts: no
  vars:
    eve_ng_ip: "10.112.62.51"
    eve_ng_username: "admin"
    eve_ng_password: "eve"
    lab_path: "/pfe.unl"
    node_id: "2"
  tasks:
    - name: Authenticate to EVE-NG and get a session cookie
      ansible.builtin.shell: |
        curl -s -c /tmp/cookie -X POST -H "Accept: application/json" -d '{"username": "{{ eve_ng_username }}", "password": "{{ eve_ng_password }}"}' http://{{ eve_ng_ip }}/api/auth/login
      register: auth_response

    - name: Debug authentication response
      ansible.builtin.debug:
        var: auth_response

    - name: Start the node using curl
      ansible.builtin.shell: |
        curl -s -b /tmp/cookie -X GET -H "Content-type: application/json" http://{{ eve_ng_ip }}/api/labs{{ lab_path }}/nodes/{{ node_id }}/start
      register: start_node_response

    - name: Debug start node response
      ansible.builtin.debug:
        var: start_node_response
