- name: Apply switch configuration - SW7v
  hosts: switch
  gather_facts: no
  connection: network_cli

  tasks:

    - name: Configure AAA
      ios_command:
        commands:
          - conf t
          - aaa new-model
          - aaa group server radius ise-group
          -  server name ISE
          - aaa authentication dot1x default group ise-group
          - aaa authorization network default group ise-group
          - aaa authorization auth-proxy default group ise-group
          - aaa accounting update periodic 5
          - aaa accounting dot1x default start-stop group ise-group
          - aaa server radius policy-device
          - aaa server radius dynamic-author
          -  client 150.1.7.130 server-key aaaakey
          -  server-key aaaakey
          - aaa session-id common
          - end

    - name: Configure IP DHCP
      ios_command:
        commands:
          - conf t
          - ip dhcp excluded-address 5.2.38.0 5.2.38.9
          - ip dhcp pool Branch
          -  network 5.2.38.0 255.255.255.0
          -  default-router 5.2.38.1
          -  dns-server 150.1.7.10
          - end

    - name: Enable dot1x system-wide
      ios_command:
        commands:
          - conf t
          - dot1x system-auth-control
          - end

    - name: Configure Spanning Tree
      ios_command:
        commands:
          - conf t
          - spanning-tree mode pvst
          - spanning-tree extend system-id
          - end

    - name: Configure Ethernet0/0
      ios_command:
        commands:
          - conf t
          - interface Ethernet0/0
          - switchport trunk encapsulation dot1q
          - spanning-tree portfast edge trunk
          - end

    - name: Configure Ethernet0/1 (dot1x + mab)
      ios_command:
        commands:
          - conf t
          - interface Ethernet0/1
          - switchport access vlan 308
          - switchport mode access
          - authentication event fail action next-method
          - authentication event server dead action reinitialize vlan 308
          - authentication host-mode multi-auth
          - authentication order dot1x mab
          - authentication priority dot1x mab
          - authentication port-control auto
          - authentication periodic
          - authentication violation restrict
          - mab
          - dot1x pae authenticator
          - spanning-tree portfast edge
          - end

    - name: Configure Ethernet0/2 as routed port
      ios_command:
        commands:
          - conf t
          - interface Ethernet0/2
          - no switchport
          - ip address 192.168.100.7 255.255.255.0
          - end

    - name: Configure Vlan1
      ios_command:
        commands:
          - conf t
          - interface Vlan1
          - ip address 151.1.7.37 255.255.255.0
          - end

    - name: Configure Vlan308
      ios_command:
        commands:
          - conf t
          - interface Vlan308
          - ip address 5.2.38.1 255.255.255.0
          - end

    - name: Configure EIGRP routing
      ios_command:
        commands:
          - conf t
          - router eigrp 4
          - network 5.2.38.0 0.0.0.255
          - network 192.168.100.0
          - end

    - name: Configure IP services
      ios_command:
        commands:
          - conf t
          - ip forward-protocol nd
          - ip http server
          - ip route 0.0.0.0 0.0.0.0 150.1.7.251
          - ip ssh server algorithm encryption aes128-ctr aes192-ctr aes256-ctr
          - ip ssh client algorithm encryption aes128-ctr aes192-ctr aes256-ctr
          - end

    - name: Configure ACL-DEFAULT
      ios_command:
        commands:
          - conf t
          - ip access-list extended ACL-DEFAULT
          - permit udp any eq bootpc any eq bootps
          - permit udp any any eq domain
          - permit icmp any any
          - deny ip any any log
          - end

    - name: Configure RADIUS and Logging
      ios_command:
        commands:
          - conf t
          - ip radius source-interface Vlan1
          - logging source-interface Vlan1
          - logging host 150.1.7.130 transport udp port 20514
          - logging host 150.1.7.130
          - radius-server attribute 6 on-for-login-auth
          - radius-server attribute 6 support-multiple
          - radius-server attribute 8 include-in-access-req
          - radius-server attribute 25 access-request include
          - radius server ISE
          -  address ipv4 150.1.7.130 auth-port 1812 acct-port 1813
          -  key aaaakey
          - end

    - name: Save Configuration
      ios_command:
        commands:
          - write memory

